name: new

on:
  workflow_dispatch:

jobs:
  cont:
    runs-on: ubuntu-latest
    steps:
      - name: repo
        run: echo "this is repo ${{ github.repository }}"
      - name: runner
        run: echo "this is architecture ${{runner.arch}}"
      - name: job
        run: echo "this is job status ${{job.status}}"
        
      
